version: '3.8'
volumes:
  exclude: #空のVolumeを追加
services:
  # ===============================================
  # Apacheの設定
  # ===============================================
  apache:
    # コンテナの中を操作するコマンドが書かれている「Dockerfile」までのディレクトリパス
    build: './infra/docker/web'
    # 自分のPCとコンテナをつなぐ設定
    volumes:
      - ./laravel_project/:/var/www/html/:delegated
      - ./infra/docker/web/conf/apache.conf:/etc/httpd/conf/httpd.conf
      - exclude:/var/www/html/.git
    # 自分のPCからコンテナにつなぐときのポート番号
    ports:
      - 8080:80
    tty: true
    privileged: true
    command: /sbin/init
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_project
      - DB_USERNAME=root
      - DB_PASSWORD=root
    external_links:
      - mysql  # 参照先コンテナ名を指定。エイリアスもつけられる

  # ===============================================
  # MySQLの設定
  # ===============================================
  mysql:
    container_name: mysql
    build: './infra/docker/mysql'
    #restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql:cached
    environment:
      - MYSQL_DATABASE=laravel_project # todo:プロジェクトに合わせて適宜調整
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
